spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001

spring:
  profiles: dev #dev环境
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称，这里使用的是映射ip 127.0.0.1名称，改c盘 etc里的host文件
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:                    #注册中心的地址，不指定的话默认是 http://localhost:8761，下面是让你看看引用的表达式
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001

spring:
  profiles: test #测试环境
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称，这里使用的是映射ip 127.0.0.1名称，改c盘 etc里的host文件
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:                    #注册中心的地址，不指定的话默认是 http://localhost:8761，下面是让你看看引用的表达式
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7001.com:7001/eureka/
